### ISSUE TITLE
SMTP Auth Issue

### ISSUE THREAD

**Issue by gte773h** [TerbiumLabs/check-reserved-instances#28]
First off, thank you for putting this project together. I find it really difficult to keep track of our reserved instance coverage.

After doing a pip install, I couldn't get the config.ini to work with our SMTP. It would produce the error below. When I replaced line 90 in report.py with:

`smtp.login(str(smtp_user), str(smtp_password))`

The error below went away. My understanding is there is a problem in smtplib and unicode strings.

Traceback (most recent call last):
  File "/usr/local/bin/check-reserved-instances", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/check_reserved_instances/__init__.py", line 96, in cli
    report_results(current_config, report)
  File "/usr/local/lib/python2.7/dist-packages/check_reserved_instances/report.py", line 90, in report_results
    smtp.login(smtp_user, smtp_password)
  File "/usr/lib/python2.7/smtplib.py", line 607, in login
    (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
  File "/usr/lib/python2.7/smtplib.py", line 571, in encode_cram_md5
    response = user + " " + hmac.HMAC(password, challenge).hexdigest()
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode

**Comment by adamstauffer** [comment]
yeah the config code we have is not great. should be swapped out to something more modern using a library that can serialize/deserialize properly. my guess is that ConfigParser sent it as some other type that smtplib cant handle. coercing it to string is an okay workaround temporarily

im going to leave this open to track the work of refactoring the config handling/parsing module
